apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hotel-svc
  name: hotel-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hotel-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hotel-svc
    spec:
      containers:
      - image: tylertreat/hotel-service
        imagePullPolicy: Always
        name: hotel-svc
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: hotel-svc
  name: hotel-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    run: hotel-svc
  sessionAffinity: None
  type: ClusterIP
